### ISSUE TITLE
Bluez 5.64

### ISSUE THREAD

**Issue by wferrara** [muka/go-bluetooth#160]
Hi,
I've a code using tinygo.org/x/bluetooth (which rely on this library) that with bluez v5.55 works flawlessly. 

Trying to run it on Ubuntu 22.04 - which has bluez 5.64 - fails while discovering the Characteristics, with message: _MapToStruct: Field not found: MTU_

Is there a way to make it work on 5.64 too?

**Comment by jacalvo** [comment]
I think the issue is that `master` only works with bluez <=5.60, I had this same issue with 5.64 and downgrading to 5.60 worked for me.

But later I've tried with `go get github.com/muka/go-bluetooth@bluez-5.63` without downgrading and that version seems to work with 5.64 too. Or at least the MTU issue is gone, not sure if they may be others if that version is not officially supported yet, but I haven't found any so far.
