### ISSUE TITLE
Any way to issue a "Powered" command?

### ISSUE THREAD

**Issue by dangerousHobo** [muka/go-bluetooth#17]
Hello,

I'm looking for a way to issue the "Powered" command (from the "Set Powered Command" section in mgmt-api.txt). Is there a way to issue a Powered on, Powered off with the current API?

Thanks.

**Comment by muka** [comment]
Hi, I think this related to the hci command socket which is not implemented
as of now.

I was looking at those to enable device services from bluetoothd api

If you have material to work on I'd be happy to work on it

sent from my phone

Il 09 ott 2017 10:35 PM, "Michael John" <notifications@github.com> ha
scritto:

**Comment by dangerousHobo** [comment]
I'm using this package in a project for my employer. Currently mainly interested in the device properties, but it would be nice to issue commands like what is available via bluetoothctl and hcitool.

If you have anything I'd be happy to test it out on our embedded system (Linux 4.1, BlueZ 5.42, LSR TiWi5 wifi/bluetooth radio).

**Comment by muka** [comment]
Thank you for your availability

Nothing available yet, you may run hci cli commands from go as done in
linux/hciconfig.go

Not optimal but helps to get things done.

The protocol to talk via hci socket need some study before implementing
anything, will put in my to-do list as it may enable other features also

sent from my phone


Il 10 ott 2017 15:48, "Michael John" <notifications@github.com> ha scritto:

I'm using this package in a project for my employer. Currently mainly
interested in the device properties, but it would be nice to issue commands
like what is available via bluetoothctl and hcitool.

If you have anything I'd be happy to test it out on our embedded system
(Linux 4.1, BlueZ 5.42, LSR TiWi5 wifi/bluetooth radio).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/muka/go-bluetooth/issues/17#issuecomment-335478031>,
or mute
the thread

**Comment by muka** [comment]
Opened #21 for progresses on the topic
